shape: [
  [
    [0.0, 0.0, 5.0],
    [0.0, 0.0, 10.0],
    [0.0, 0.0, 15.0],
    [0.0, 0.0, 20.0],
    [5.0, 0.0, 20.0],
    [8.0, 0.0, 15.0],
    [3.0, 0.0, 7.5],
    [5.0, 0.0, 5.0]
  ],
  [
    [0.0, 0.0, 5.0],
    [5.0, 0.0, 5.0],
    [10.0, 0.0, 5.0],
    [5.0, 0.0, 10.0],
    [5.0, 0.0, 15.0],
    [5.0, 0.0, 20.0],
    [0.0, 0.0, 20.0],
    [10.0, 0.0, 20.0]
  ],
  [
    [3.0, 0.0, 7.5],
    [5.0, 0.0, 5.0],
    [10.0, 0.0, 7.5],
    [7.5, 0.0, 10.0],
    [5.0, 0.0, 12.5],
    [3.0, 0.0, 17.5],
    [5.0, 0.0, 20.0],
    [10.0, 0.0, 17.5]
  ],
  [
    [5.0, 0.0, 5.0],
    [7.5, 0.0, 5.0],
    [10.0, 0.0, 7.5],
    [3.0, 0.0, 10.0],
    [3.0, 0.0, 15],
    [5.0, 0.0, 20.0],
    [7.5, 0.0, 20.0],
    [10.0, 0.0, 17.5]
  ]

]
# wait time for each shape before transitioning to the next, [seconds]
# if only one duration is provided, it will be used for all shapes
durations: [1.0]
