shape: [
  [
    [10.0, 20.0, 15.0],
    [15.0, 20.0, 15.0],
    [20.0, 20.0, 15.0],
    [15.0, 20.0, 10.0],
    [15.0, 20.0, 7.0],
    [15.0, 20.0, 3.0]
  ],
  [
    [10.0, 10.0, 5.0],
    [15.0, 10.0, 5.0],
    [20.0, 10.0, 5.0],
    [25.0, 10.0, 5.0],
    [30.0, 10.0, 5.0],
    [35.0, 10.0, 5.0]
  ]

]
# wait time for each shape before transitioning to the next, [seconds]
# if only one duration is provided, it will be used for all shapes
durations: [5.0]
